services:
  dcs-postgres:
    image: postgres:17.4-alpine
    container_name: urb-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: urbanizapassword
      POSTGRES_USER: urbanizapostgres
    ports:
      - 5433:5432
    volumes:
      - urb_postgres_data:/var/lib/postgresql/data
    networks:
      - local-network

#  my-app:
#    build: .
#    container_name: urbanizaApplication
#    restart: always
#    depends_on:
#      - dcs-postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://dcs-postgres:5432/postgres
#      SPRING_DATASOURCE_USERNAME: urbanizapostgres
#      SPRING_DATASOURCE_PASSWORD: urbanizapassword
#    ports:
#      - 8282:8080
#    networks:
#      - local-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: urb-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@urbaniza.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8083:80
    volumes:
      - urb_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - dcs-postgres
    networks:
      - local-network

volumes:
  urb_postgres_data:
  urb_pgadmin_data:

networks:
  local-network:
    external: true