version: '3.8'

services:
  dcs-postgres:
    image: postgres:17.4-alpine
    container_name: urb-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: urbanizapassword
      POSTGRES_USER: urbanizapostgres
      POSTGRES_DB: urbaniza_db  # Adicionei um nome para o banco de dados
    ports:
      - 5433:5432
    volumes:
      - urb_postgres_data:/var/lib/postgresql/data
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: urb-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@urbaniza.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    ports:
      - 5050:80
    volumes:
      - urb_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - dcs-postgres
    networks:
      - local-network

  my-app:
    build: .
    container_name: urbanizaApplication
    restart: always
    depends_on:
      - dcs-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dcs-postgres:5432/urbaniza_db
      SPRING_DATASOURCE_USERNAME: urbanizapostgres
      SPRING_DATASOURCE_PASSWORD: urbanizapassword
    ports:
      - 8282:8080
    networks:
      - local-network

volumes:
  urb_postgres_data:
  urb_pgadmin_data:

networks:
  local-network:
    driver: bridge