services:
  urbdb:
    image: postgres:17.4-alpine
    container_name: urbdb
    restart: always
    environment:
      POSTGRES_PASSWORD: urbanizapassword
      POSTGRES_USER: urbanizapostgres
      POSTGRES_DB: urb-db
    ports:
      - 5433:5432
    volumes:
      - urb_postgres_data:/var/lib/postgresql/data
    networks:
      - local-network

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: urbaniza
    container_name: urbaniza
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U urbanizapostgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://urbdb:5432/urb-db
      SPRING_DATASOURCE_USERNAME: urbanizapostgres
      SPRING_DATASOURCE_PASSWORD: urbanizapassword
    ports:
      - 8282:8081
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: urb-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@urbaniza.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8083:80
    volumes:
      - urb_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - urbdb
    networks:
      - local-network

volumes:
  urb_postgres_data:
  urb_pgadmin_data:

networks:
  local-network:
    external: true
